name: Master CI

on:
  pull_request:
    branches:
      - master

# If a new commit is pushed before the old one's CI has completed (on the same branch), abort previous run
concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  all:
    name: All

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    runs-on: ${{matrix.os}}

    env:
      RUSTFLAGS: --deny warnings

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust Toolchain Components
        uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: Test
        run: cargo test --all

      - name: Clippy
        run: cargo clippy --all --all-targets

      - name: Format
        run: cargo fmt --all --check

      - name: Build
        run: cargo build
