name: Release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+*

jobs:
  release:
    name: Publish to Github Releases
    permissions:
      contents: write

    strategy:
      matrix:
        include:
          - target: aarch64-apple-darwin
            os: macos-latest
            use-cross: true
            cargo-flags: ""
          - target: x86_64-apple-darwin
            os: macos-latest
            cargo-flags: ""
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            use-cross: true
            cargo-flags: ""
          - target: i686-unknown-linux-musl
            os: ubuntu-latest
            use-cross: true
            cargo-flags: ""
          - target: aarch64-unknown-linux-musl
            os: ubuntu-latest
            use-cross: true
            cargo-flags: ""
    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v2
        id: git-cliff
        with:
          config: cliff.toml
          args: -vv --latest --strip header
        env:
          OUTPUT: CHANGELOG.md

      - name: Install Rust Toolchain Components
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Show Version Information (Rust, cargo, GCC)
        shell: bash
        run: |
          gcc --version || true
          rustup -V
          rustup toolchain list
          rustup default
          cargo -V
          rustc -V

      - name: Build
        shell: bash
        env:
          target: ${{ matrix.target }}
          version: ${{ github.ref##*/ }}
        run: |
          cargo build --locked --release --target=${{ matrix.target }} ${{ matrix.cargo-flags }}
          bin=${GITHUB_REPOSITORY##*/}
          alias_bin="pikpakcli"
          name=$alias_bin-$version-$target
          mv target/$target/release/$bin target/$target/release/$name
          echo "cmd=target/$target/release/$name" >> $GITHUB_OUTPUT

      - name: Publish
        uses: softprops/action-gh-release@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          draft: false
          files: |
            ${{ steps.package.outputs.cmd }}
          body: ${{ steps.git-cliff.outputs.content }}
          tag: ${{ github.ref }}
          token: ${{ secrets.TOKEN }}
