name: Release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+*

jobs:
  release:
    name: Publish to Github Releases
    permissions:
      contents: write

    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            use-cross: true
            cargo-flags: ""
          - target: aarch64-unknown-linux-musl
            os: ubuntu-latest
            use-cross: true
            cargo-flags: ""
          - target: i686-unknown-linux-musl
            os: ubuntu-latest
            use-cross: true
            cargo-flags: ""
          - target: armv7-unknown-linux-musleabihf
            os: ubuntu-latest
            use-cross: true
            cargo-flags: ""
          - target: arm-unknown-linux-musleabihf
            os: ubuntu-latest
            use-cross: true
            cargo-flags: ""
          - target: aarch64-apple-darwin
            os: macos-latest
            use-cross: true
            cargo-flags: ""
          - target: x86_64-apple-darwin
            os: macos-latest
            cargo-flags: ""


    runs-on: ${{matrix.os}}
    env:
      BUILD_CMD: cargo

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Rust Toolchain Components
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install cross
        if: matrix.use-cross
        uses: taiki-e/install-action@v2
        with:
          tool: cross

      - name: Overwrite build command env variable
        if: matrix.use-cross
        shell: bash
        run: echo "BUILD_CMD=cross" >> $GITHUB_ENV

      - name: Show Version Information (Rust, cargo, GCC)
        shell: bash
        run: |
          gcc --version || true
          rustup -V
          rustup toolchain list
          rustup default
          cargo -V
          rustc -V

      - name: Build
        shell: bash
        id: build
        env:
          target: ${{ matrix.target }}
        run: |
          $BUILD_CMD build --no-default-features --features=rustls --locked --release --target=${{ matrix.target }} ${{ matrix.cargo-flags }}
          ver=${GITHUB_REF##*/}
          bin="pikpakcli"
          name=$bin-$ver-$target
          mv target/$target/release/$bin target/$target/release/$name
          echo "cmd=target/$target/release/$name" >> $GITHUB_OUTPUT

      - name: Publish
        uses: softprops/action-gh-release@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          draft: false
          files: ${{ steps.build.outputs.cmd }}
          token: ${{ secrets.GITHUB_TOKEN }}
